### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by goloroden** [pvorb/node-crypt#3]
Hi there 😊!

As I have seen, you have added the missing license information to this package, but unfortunately this was after the `0.0.1` release.

Would you mind publishing a new release that contains these information?

Currently, our build fails, since our license checker is not able to defer the license from your `package.json` file.

**Comment by pvorb** [comment]
Sure, I've released v0.0.2

**Comment by goloroden** [comment]
Great, thanks 😊
